### PR TITLE
Use chi/v5 middleware consistently

### PR DESCRIPTION
**Pull request by rillian**
This unversioned import keeps trying to add the old chi v1 package; use the same versioned reference we have in enclave.go.

### CODE REVIEW

**Comment by rillian** [comment]
I think this was why you were getting the extra `chi` in go.mod.

**Comment by DJAndries** [comment]
Yes, I saw this. decided to handle this in a second PR. thanks for raising it. have you tested it? does the metrics server still work?

**Comment by rillian** [comment]
I have not tested it.

**Comment by rillian** [comment]
@DJAndries I've tested this and confirmed it works locally.

**Review by DJAndries — APPROVED** [review]

**Pull request merged**
